version: '2'
services:
  elasticsearch:
    build: elasticsearch-docker/
    restart: unless-stopped
    volumes:
      - ./es-data/:/usr/share/elasticsearch/data
      - ./es-config/:/usr/share/elasticsearch/config/
    ports:
      - "9200:9200"

  mongo:
    image: mongo:3.3
    restart: unless-stopped
    volumes:
      - ./mongo-data/:/data/db

  graylog2:
    image: graylog2/server:2.0.3-2
    restart: unless-stopped
    links:
      - elasticsearch:elasticsearch
      - mongo:mongo
    depends_on:
      - mongo
      - elasticsearch
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    ports:
      - "9000:9000"
      - "12900:12900"
      - "12201/udp:12201/udp"
      - "12201/tcp:12201/tcp"
      - "1514/udp:1514/udp"
    volumes:
      - ./graylog/data/journal:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
